# Generated by Django 4.0 on 2023-06-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=100)),
                ('campo2', models.IntegerField()),
                ('campo3', models.DateField()),
                ('region', models.CharField(max_length=100)),
                ('gobernacion_maritima', models.CharField(max_length=100)),
                ('capitania_puerto', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Informacion',
            },
        ),
    ]
