# Generated by Django 4.2.2 on 2023-06-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacion',
            name='campo1',
        ),
        migrations.RemoveField(
            model_name='informacion',
            name='campo2',
        ),
        migrations.RemoveField(
            model_name='informacion',
            name='campo3',
        ),
    ]
